想想这个世界还有什么需要维护的
迅速读完书籍



* 适合朋友圈的广告
* 做一个编辑器

https://zhuanlan.zhihu.com/p/166375631

对，proxychains 的功能远远不止于达到换源的效果。比如你想FQ ，可以直接 proxychains /usr/bin/chrome-stable --no-sandbox 达到效果，或者git clone something，连接海外小鸡SSH 加速

* 英语
  
《don't cry 》：这首歌曾唱哭了千万人。总是能够触痛了心底最软的地方，心抽痛着，眼圈红了，却没有眼泪渗出，每多听一次就多一次的依恋。

《fade to black》：金属乐队也有很经典歌曲，国内有很多人都是听了这首歌的前奏才去学吉他的!METALLICA经典中的经典,也是METALLICA饱受争议的作品,因为当时有乐迷自杀就是出于这首歌。

《dreaming my dream》：有着王菲一样变幻倚俪的唱腔，高雅离开了原本浩渺的苍穹来到人间，它带着冷漠的美艳，但又说着人身上的变动和永恒，爱尔兰的卡百利乐队就这样汲取了精灵与传说的浩渺气质，沟通了人间和天空的美，把人的故事，爱情，历史，死亡，社会都融进那飘忽而真切的女声中。

《dying in the sun》：不断地重复着放这首歌,简短迂回的旋律,简短迂回的歌词。渴望在阳光下睡死。

《never grow old》：当你感觉自己在一天一天的虚度光阴时，就会不由得想起了这支歌!

《far away from home》：德国新晋乐队,这首歌已被众多知名DJ誉为当今舞曲最为精华的传世之作，听了不下几百遍了，旋律很好。

《knocking on heaven's door》：艾薇儿翻唱的都给人一种爽歪的感觉，当然女生版的更加恬静。

《imagine》约翰列侬是全世界最成功的摇滚乐队“甲壳虫”（beatles）的灵魂人物，死于1980年12月8日，是被一名狂热的歌迷开枪打死的，他的死震惊了世界，他在六十年代吸毒，目无宗教和政府，在七十年代致力研究东方宗教和宣扬童话般的爱（有一颗小星星是以他的名字命名的），这声音听来象预言者的祈祷，而歌词依然是固执的理想，或许列侬所要求的太过绝对，太过纯洁，但作为梦，难道你我就不曾有过吗？

《yesterday》：beatles这么经典的还说什么呢，电台点播率已经超过一亿次了。

《let it be》：beatles昔日创下了榜史纪录,也是Beatles解散时成员们的心态写照。有时候生命的意义在于过程,至于结果就让它Let it be。

《it's my life》：邦.乔维比较早的一首歌，曾用来做CS的MTV背景音乐。

《that's why you go away》：半路在一家美发店的门前听到了的钢琴版!感觉很好，这样听起来That s why就更经典了!

《you can't say》：旋律一起就能体会其中的柔情。

《yesterday yes a day》：温柔醇厚的声音,静静地用心体会,很舒服的21岁的挪威女孩marlin,自己写歌自己唱,一首充满浪漫气息的法国歌曲,就像爱人在你耳边轻轻呢喃。

《heal the world》：他是疯狂热爱和不羁职责的承受者，年轻的巨富，心理怪异而各声纯洁的奇人，他富于创造，不向任何一个流派靠拢，虽然杰克逊现在的形象不好,但他曾经为世界的慈善事业作了很大的贡献,这首歌也正是他心意的表现吧。

《the girl is mine》：纯洁的仿佛童话，干净的让人不敢呼吸。

《delicious way》：仓木麻衣的歌曲，听到这么纯洁的歌曲感觉到音乐真的是没有国界。

《under the sea》：小美人鱼插曲,可总感觉张邵晗唱的更有活力。再听听原唱的，就知道东西方文化的差异在哪里了。

《fighter Christina》：厚重有力的嗓音穿透着我的耳膜,装饰着闪亮碎钻的眼眸冲击着我的视网膜，希望有一天,我能够成为那个fighter。

《without you》：我喜欢的歌星！因为她在唱功方面显得极为细腻,而且她的声线真的是性感迷人而且非常有爆发力和感染力。这是高音上唯一可与《i will always love you》媲美的歌，下面还有一首两人合唱的，绝对体现唱功。

《when you believe》不多说了，任何人都唱不成这样的。

 《Crying in the Rain》大概算的上是欧美最具生命力的情歌之一了，这首出自民谣女歌手Carole King的作品对原来舒缓深情的作品来了一次颠覆性的改造。

 《never say goodbye》：充满曼陀铃和竖琴声音的歌曲当中透显出一个宁静而美丽的少女形象，歌曲是从爱尔兰传统歌曲中改编过来，Hayley Westenra的声音如同丝线一般，在演唱技巧上更已达到完美的境地，而嗓音天生的优美更是让人不得不赞叹和艳羡。

《Sugar Ray s Someday》：他们的音乐风格用一个字就可以形容---Summer，他们只在夏天出片，歌儿一听就让人想起夏天---总是阳光明媚、活泼愉快。与此相反的，他们的歌词却是比较深的，那个身上有着13个纹身、英俊得完全不像个rock band主唱的Mark McGrath经常用很夸张的肢体语言在MTV中摇摆，加上十分十分正宗的传统摇滚式配器，恐怕在今天活着的乐队中找不出第二个这样的band。

《Iris Goo Goo Dolls》：清脆急促的吉他，John Rzeznik饱含沧桑的低沉嗓音，对世事、爱情满腹的疑问，后面的爆发，“And I don t want the world to see me, Cause I don t think that they d understand. When everything s made to be broken, I just want you to know who I am!” 这是有着无穷韵味的箴言。

《Mystical Machine Gun》比较难得的是，Kula Shaker的音乐受了很多东方思想的影响，这一点同时表现在歌词、音乐和配器之中。乐队唯一真正意义上的专辑就是《Peasants, Pigs & Astronauts》专辑干净的声音，迷幻的吉他，如印度梵音般的和声，充满现场感的录音，总之在当时背景下，属于绝对的异类。

《Elemental tears for fears》：其实只是主唱oland Orzab一个人而已，整张专辑所有词曲、每一轨录音（器乐、主唱、和声）全部出自这家伙一人之手（口），真是吓了一跳（原来世界上真的有全才啊）！

《gone away 》：the off spring是一个比较有争议的乐队。跟99%的美国摇滚乐队一样，也是来自学校同学的组合，经过很长时间的地下活动，终于走到地上，给人留下最深刻印象就是主唱Bryan Holland的十分金属化的硬朗狂放的唱腔,歌词有着对世事无情的玩弄和嘲讽。 
《A Question Of Lust》：很容易和“冷”这个字联系起来，冷冰冰的纯电子音乐，冷冷的唱腔，冷僻的歌词，似乎特别适合目前这个季节来听。 
《this is how we do it》：欢快的一首现代英文混音dj舞曲。 
《boom boom boom》：各位爱跳舞的朋友，这就是你们的音乐，做为音乐和舞蹈的信徒，你们起床要放的音乐。 
《Earth song》：请保护大自然!崇高的敬意!看过mv后真的感觉心里堵堵的。 
《everybody dance now》：相信看过韩国综艺节目情书的朋友不会陌生吧！里面好多背景音乐就是用的这个，尤其是uncle shin的抖动dance甩你的双手，很简单的一个步骤，音乐炸进你的头，活着就要开心些！ 
《the day you went away》：M2M是当之无愧的小甜甜，相信谁都不会忍心伤害这样的女生，不过歌词有点伤感，我们从来都不知道珍惜所拥有的直到永远的失去它,将如何承受这种痛苦,现在，我不得不说，我是真的真的失去了你。 
《when you say nothing at all》：Krauss多次被评为世界最美的女声,坐拥11座格莱美奖,被无数人翻唱过！ 
《hero》：enrique iglesias出生在马德里,有着西班牙人独有的深邃的双眸,冷峻而又性感的脸庞,富有磁性的嗓音,再加上他那令人神魂颠倒的外表。 
《god is a girl》：从个人角度看sweetbox和groove coverage是给我印象最深的两个女唱乐队，下面还有几首歌都是她们的，很喜欢女主唱有些慵懒而很清脆的声音,他们的风格...喜欢听这种节奏感强，比较热闹的歌曲。觉得这个乐队的风格还是挺新鲜的，也比较大众化，应该会有不少朋友会喜欢，因为大众不等于庸俗。 
《she》 
《can't get over you》 
《7 years and 50 days》 
《encore une fois》：一首抒情法语歌,哀而充满无奈的歌,你能体会到它的忧伤，也许有一天我会离开你，途跋涉寻找真的自己也许有一天，也许有一天。 
《je'm appelle》：听了首法语歌后觉得法语太美了，让人感觉说法语的人嘴上摸了奶油，于记忆深处，要我找到??。 
《here i am》：那是布赖恩.亚当斯的作品,我想大家应该都听过他那首绝对经典的歌《Everything I Do》吧，这个帅帅的沧桑男人的声音是谁都无法抗拒。 
《Everything i do》不多说了，绝对经典中的经典。 
《all that you can't leave behind》：毫无疑问，U2是80年代英国最受欢迎的摇滚乐团，不过我个人只喜欢这一首，具体也说不出为什么，可能感觉声音和旋律搭配的很棒吧。 
《big big world》：看上去是一个爱整洁的乖女孩，尤其在唱《Big Big World》这样的慢歌时，她显得十分纯情而古典。目前Emilia的唱片在瑞典已卖过了3白金的数量。而首支单曲《Big BigWorld》则成为了瑞典历史上流行速度最快的一支。 
《right here waiting》：这是一首很经典的老歌，歌唱了刻骨铭心的爱情。这是我曾经最爱的一首老歌，相信每个人也都听过无数遍。 
《stay williams》：特别特别特别的欢快。 
《live forever》：是近十年来英国最受欢迎和最受评论家承认的乐队之一。 
《life for rent》：清爽的时节，清爽的女孩儿，清爽的音乐。《Life for rent》把整个生命都出租出去，不属于任何人，无根地飘荡，听起来有一些伤感。 
《promise don't come easy》跟着CD慢慢的哼着，记不清楚是什么时候第一次听了，若有若无的思绪缠绕着自己，象梦一样。 
《lonely nana》：是一首黑人说唱歌曲，同时加入了R&B和Blues的曲风，歌曲的当中还有女声的伴唱，旋律非常优美。不会再有第二首歌可以超越歧视,家庭的破碎。 
《dilemma》：kellyrowland与饶舌巨星nelly搭档演唱的歌曲，这首歌曲虽然风格老套，但仍然在全美电台创下近两个月蝉联冠军宝座的纪录。 
《you took my heart away》：舒缓的节奏，简洁的编曲，十足的优美旋律，都展现了mltr最擅长的迷人功力。 
《encore une fois》：一首经典法语歌，同样将法国浓郁的浪漫气息，法国当红歌手helene segara专辑，她的音乐和她的人一样别有风情。她的嗓音并不是十分突出，但声音中有一种魅惑迷离的特质。 
《sealed with a kiss》：以吻封缄，经典美国乡村音乐，一首极具浪漫色彩的老歌，叙离别情，但不伤感；道分手苦，但不低沉。饱尝相思之苦的恋人们听来，肯定别有一番滋味。 
《only time》：无由的哀愁随着Only Time的歌声涌上心头。而当爱情灭绝?心泣莫名?欲盖弥彰的绝望凄清，却只有时间为唯一的目击者。 
《i will be missing you》：记得第一次听它的时候，只记得旋律很HIP-POP，直到后来无意中才知道了它的来历。 
《civil war》：在美国这样一个国度，一支摇滚乐队创作出这样一首忧国忧民（当然也可以理解成激愤）的歌曲，这不是对摇滚乐的反判，恰恰是对摇滚更好的诠释。我想，摇滚乐在国外之所以有那么高的地位正是由于国外的很多摇滚乐队有着对社会、对国家的主人精神以及对音乐的深入理解和精彩绝伦的演绎。国内呢？只有流行乐泛滥罢了，摇滚不光是非主流，几乎成末流了。 
《sunny came home》：1998年葛莱美大奖获奖作品,现在已很难找得到这样动听的旋律了. 
《the one》：Mr big每首歌曲中都有一段经典耐听的吉他SOLO。我想有这一首歌就足以流芳百世了,即使多少年以后,这首歌也会引起人们无限的共鸣。 
《to be with you》：Mr big几乎所有的吉他教材都可以看到这首《与你同在》，这首歌用木吉他超越了轰鸣，用随便超越了夸张，用一群拍着首合唱的小伙子超越了舞台上的超级巨星，时间总会流逝，浪漫和现实，究竟哪一个会与你同在呢？ 
《stop crying your heart out》：称不上经典，但是也总能给人一种疲倦到不想说什么的地步。 
《cinderella》：英文版的这首半糖主义，比SHE她们唱的好听一百倍！ 
《the sound of silence》：是奥斯卡最佳电影《毕业生》的主题歌,是美国流行音乐大师保罗.西蒙的代表，一百个人当中会有一百个人喜欢听这歌的。 
《should it matter sissel》：我喜欢这个低调又华美的女子,淡淡的感觉，仔细听可以听出性感！ 
《stuck in my heart》旋律很优美，中间有一段很完美的合声。 
《utopia》：下面三首歌都是出自sweetbox的！他们的歌曲都巧妙地融合Pop、??音乐，行?流水的律动?出女主唱Jade戏剧性的歌声，不仅开启歌迷的想像空间，而且扣人心弦。 
《alright》 
《one kiss》 
《dreams come true》ses被无数个电台做过无数次的背景电乐，旋律响起你就知道你肯定听过的。 
《sweet dream》：很喜欢的一首歌了这个MV相当不错。 
《back to you》：不多说了，布莱恩.亚当斯的每一首歌都那么经典。 
《forever and ever-because i love you》：绝对好听，因为dido就是因为这首歌红的。 
《Say It Isn't So》：邦.乔维唱的柔情歌曲也很感人。 
《now and forever》：他的歌真的很不错！ 
《angle of mine》：一个很老的乐队唱的，非常好听。 
《dream》：就是大名鼎鼎的卡百利乐队，这首《Dream》选自他们第一张专辑。 
《faint》：林肯公园,乐队名字是因为每天乐队的例行练习结束回家时，他都会驾车路过林肯公园，重要的是，他们的平均年龄不过二十出头，他们的音乐给人另类的感觉。 
《somewhere i belong》：林肯公园节奏快然后有点另类的歌。 
《妖精》：开朗轻快的曲风很讨人喜欢，名字是不好听了一点点，但整首歌却是有一点我行我素，特立独行并不会为任何人改变。 
《westlife》：很喜欢Westlife的歌,每天在他们的歌声中吃饭，看书，入睡。 
《the power of love》提起席琳.迪翁，大家都知道她的演唱以倾情投入而闻名于世，她的音色极具表现力，声域宽广，很有张力，最喜欢的歌曲，完美的歌曲。 
《a new day has come》：她以满腔的爱与希望蕴育出另一个炽热的生命，她歌唱生涯中第八张英文专辑《a new day has come》在细腻悠扬、情感丰沛的歌声中，感受到旺盛的生命能量，热烈地传送到世界每个角落。 
《more than words extreme》：被翻唱了无数遍的歌，只用一把木吉他伴奏，但他高贵的气质却随着真情流露，胜过了有着华丽织体的热闹声音，当然，这首歌最迷人的，还是天衣无缝的合声部分 那轻轻的，起伏的，隐现并滑翔而逝的伴唱，只有真正胸怀开阔，品位脱俗的人才能这样写情歌，也只有真正温柔可爱的人才值得被这样的歌声围绕。 
《killing me softly with his song》：由于年代久远，这首歌不可避免地带上了留声机时代遗留下来的贵族味道，一遍遍地重复“killing me softly with his song”，她已经醉了，已经无力逃脱了，她更象是自言自语，捧着胸口喃喃自语而脑子里眼睛里全是他。 
《can you feel the love tonight》：埃尔顿.约翰工整清晰的吐字，彬彬有礼的抒情，不紧不慢的钢琴，只能有那些拥有严谨文化传统的中老年英国人来展现。 
《lemon tree》：5个德国小伙子组成的“傻子花园”乐队。 
《vincent》：这位歌词有着诗一样已经的青年为人了精神殉道者，荷兰后印象派画家，伟大的疯子文森特.梵高献上了感人的一曲，这首歌唱到了艺术家的孤独和世人的不义，唱到了崇高的痛苦和爱，唱到了内心矛盾，唱到了神，宁静和永远。 
《one love》：他用歌声带给人快乐，并为公正而斗争，这样的一生足以使任何一位歌者在死神面前保持尊严，牙买加总统参加了他的葬礼。 
《careless whisper》：威猛是中国改革开放以来最早接受的西方流行音乐，现在听来真的是别有一番滋味。 
《don't cry for me，argentina》：麦当娜她卖弄性感，当她撕开人们的虚伪时，我们听到的是一副越唱越好的嗓子，和一种越来越真实的性格。阿根廷前总统夫人依维塔确有一生传奇的经历 寒门女子最终身居国母，用圣洁的博爱感动了整个国家，她为穷人所做的一 
《two steps behind defleppard》：KB海峡拥有高超的不鲁斯吉他技巧，低沉嗓音的半说半唱，成熟睿智的歌词，以及难以言表的宽厚情怀，整个八十年代，不知多少人依靠他们的音乐，完成了由青春向成年的过渡，不知多少人被那悠远延绵的意境带走，超脱于现实的无聊纷争。 
《no more i love you》：此人于1995年推出了专辑《美杜莎》。美杜莎，是希腊女神中最狰狞古怪的一个，把超人的魔力给了这个歌手，让她有力，跌宕起伏，在我们想象之上拖曳高音，延续着从唯美派文学到新古典音乐的影响，也徘徊在艺术和商业之间，沟通着尘世的想象。 
《my heart will go on》：这是即使小学生也听过而且非常喜欢的一首歌。 
《missing you now》：这个男人具有轻易征服听众的才能，曾是美国电台播放给“面的”司机听的最佳人选，可以用最直接的方法来美化我们的听觉，而且，我们根本无须费心去听，只要跟着，哼着，忙自己的，快乐就产生了。 
《yesterday once more》：唱者卡伦.卡彭特被称为美国的邓丽君，当她死于神经性厌食症时，人们突然发现，在所有那些包装精良，华美诱人的热门金曲中，可能只有卡伦卡彭特的声音值得被收藏，她把悠长的旋律唱得光芒耀眼，即使怀旧，都充满了对生活的感恩，她的歌声始终在呼唤人们热爱的本能。 
《goodbye》：80年代最受欢迎的一对组合,他们高低的配合优美的歌词动听的旋律令人难以抗拒。喜欢这样凄美华丽的声音，唱出那句痛彻心肺的“There's no other way than to say goodbye” 
《your song》：平滑流畅的钢琴和埃尔顿.约翰淡淡柔情的演唱，似乎就是和爱人相拥坐在黄昏中的木屋顶，看远处夕阳西下，与世上最最甜美的双眸对望，任似水年华静静流淌，这时不用很多钱，不用大房子，只要有一首由爱人所唱，但却只属于自己的歌就足够了。 
《hotel california》我喜欢那充满磁性的嗓音，木吉他弹奏出简单幽怨的调子外，我想，喜欢它的另一个理由便是对回忆的孤独感受。这样的曲子，适合一个人听，一遍又一遍地重听，随乐韵飘荡到广袤却寂寥的。

